spring:
  profiles:
    active: dev
  application:
    name: summer-compute
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:9527/eureka/,http://peer2:9528/eureka/,http://peer3:9529/eureka/