server:
  port: 8081
  servlet:
    context-path: /summer
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/summer?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    username: 1756330108@qq.com
    password: qxkusgfdmsltcdbg
    default-encoding: utf-8
    host: smtp.qq.com
summer:
  resources:
    root-dir: D:/summer/resource_root
    prefix: /resource
    pic-dir: /pic
    audio-dir: /audio
    video-dir: /video
  file-service:
    service-type: local
    res-url-prefix: /resource
    context-path: ${server.servlet.context-path}
    s3: #Amazon S3配置
      access-key: fd809d16971e45a8923dc8a75b526235
      secret-key: ba64ea97f882444b9d30082bb638de62
      endpoint: http://s3.bj.bcebos.com
      signing-region: bj
      s3-root-bucket-name: dong-box
      path-seperator-replacor: SUMMER
    local:
      res-root-dir: ${summer.resources.root-dir}
  mail:
    subject: About Love
    content: summer is coming，summer is coming
    from-address: 1756330108@qq.com
    to-address: 1756330108@qq.com
    # 开发调试  每分钟  0 0/1 * * * ?   每天  0 0 0 1/1 * ?
    cron: 0 0 0 1/1 * ?